[tool.poetry]
name = "anura-data-model"
version = "0.1.0"
description = "Data model for Anura Protobuf format"
authors = ["Erik Finnman <erik.finnman@layer10.se>"]
readme = "README.md"
packages = [{include = "generated"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
