name: Anura Gateway reusable workflow

on:
  workflow_dispatch:
  push:

concurrency: ${{ github.workflow }} # Do not permit concurrent builds for the same workflow

jobs:
  generate_model:
    name: Generate model
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.OIDC_ROLE_AWS_REGION }}

      - name: Use CodeArtifact for pip dependencies
        run: |
          aws codeartifact login --tool pip --domain revibe-energy  --repository revibe-repo

      - name: Install buf tooling
        uses: bufbuild/buf-setup-action@v1.17.0

      - name: Generate Python implementation
        run: |
          buf generate model

